pre-release-commit-message = "chore: release"
tag-message = "{{tag_name}}"
tag-name = "v{{prefix}}-v{{version}}"
pre-release-hook = ["./hook.sh"]
consolidate-commits = false
consolidate-pushes = true
allow-branch = ["master"]
