[package]
name = "v_latexescape"
version = "0.4.3"
authors = ["Rust-iendo Barcelona <riendocontributions@gmail.com>"]
description = "The simd optimized LaTeX escaping code"
documentation = "https://docs.rs/v_latexescape"
edition = "2018"
keywords = ["latex", "escaping", "simd"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://gitlab.com/r-iendo/v_escape"
workspace = ".."

[badges]
gitlab = { repository = "r-iendo/v_escape" }
maintenance = { status = "actively-developed" }

[lib]
name = "v_latexescape"
path = "src/lib.rs"
bench = false

[dependencies]
v_escape = { version = "0.7", path = "../v_escape" }
cfg-if = "0.1"

[build-dependencies]
v_escape = { version = "0.7", path = "../v_escape" }
