[package]
name = "v_htmlescape"
version = "0.4.4"
authors = ["Juan Aguilar Santillana <mhpoin@gmail.com>"]
description = "The simd optimized HTML escaping code"
documentation = "https://docs.rs/v_htmlescape"
edition = "2018"
keywords = ["html", "escaping", "simd"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/r-iendo/v_escape"
workspace = ".."

[badges]
travis-ci = { repository = "botika/v_escape", branch = "master" }
maintenance = { status = "actively-developed" }

[lib]
name = "v_htmlescape"
path = "src/lib.rs"
bench = false

[dependencies]
v_escape = { version = "0.7", path = "../v_escape" }
cfg-if = "0.1"
