[package]
name = "v_escape"
version = "0.7.3"
authors = ["Juan Aguilar Santillana <mhpoin@gmail.com>"]
description = "The simd optimized escaping code"
documentation = "https://docs.rs/v_escape"
edition = "2018"
keywords = ["escaping", "simd"]
license = "MIT/Apache-2.0"
readme = "../README.md"
repository = "https://github.com/r-iendo/v_escape"
workspace = ".."

[badges]
travis-ci = { repository = "botika/v_escape", branch = "master" }
maintenance = { status = "actively-developed" }

[lib]
name = "v_escape"
path = "src/lib.rs"
bench = false

[dependencies]
v_escape_derive = { version = "0.5", path = "../v_escape_derive" }
