[package]
name = "v_escape"
version = "0.7.2"
authors = ["Rust-iendo Barcelona <riendocontributions@gmail.com>"]
description = "The simd optimized escaping code"
documentation = "https://docs.rs/v_escape"
edition = "2018"
keywords = ["escaping", "simd"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://gitlab.com/r-iendo/v_escape"
workspace = ".."

[badges]
gitlab = { repository = "r-iendo/v_escape" }
appveyor = { repository = "botika/v_escape" }
maintenance = { status = "actively-developed" }

[lib]
name = "v_escape"
path = "src/lib.rs"
bench = false

[dependencies]
v_escape_derive = { version = "0.5", path = "../v_escape_derive" }
version_check = "0.1"

[build-dependencies]
version_check = "0.1"
